package db.ecommerce.model.tables;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import db.ecommerce.model.Courier;
import db.ecommerce.model.CourierPK;
import db.ecommerce.utils.DateConverter;

public class CourierTable implements Table<CourierPK, Integer> {

    private final Connection conn;
    private final static String TABLE_NAME = "CORRIERI";

    /**
     * @param conn the connection to the db
     */
    public CourierTable(Connection conn) {
        this.conn = conn;
    }

    @Override
    public String getTableName() {
        return TABLE_NAME;
    }

    @Override
    public boolean createTable() {
        final String query = "CREATE TABLE" + TABLE_NAME + "(" + "Cod_corriere int not null auto_increment,"
                + "Codice_fiscale char(16) not null," + "Nome varchar(20) not null," + "Cognome varchar(20) not null,"
                + "Data_di_nascita date not null," + "Cod_patente varchar(20) not null,"
                + "Nazionalità_patente varchar(25) not null," + "constraint IDCORRIERE_1 primary key (Cod_corriere))";
        try (final PreparedStatement statement = this.conn.prepareStatement(query)) {
            statement.executeUpdate(query);
            return true;
        } catch (final SQLException e) {
            return false;
        }
    }

    @Override
    public boolean dropTable() {
        final String query = "DROP TABLE " + TABLE_NAME;
        try (final PreparedStatement statement = this.conn.prepareStatement(query)) {
            statement.executeUpdate(query);
            return true;
        } catch (final SQLException e) {
            return false;
        }
    }

    @Override
    public Optional<CourierPK> findByPrimaryKey(Integer primaryKey) {
        final String query = "SELECT * FROM " + TABLE_NAME + " WHERE Cod_corriere=?";
        try (final PreparedStatement statement = this.conn.prepareStatement(query)) {
            statement.setInt(1, primaryKey);
            var result = statement.executeQuery();
            return convertResultSet(result).stream().findFirst();
        } catch (final SQLException e) {
            return Optional.empty();
        }
    }

    private List<CourierPK> convertResultSet(ResultSet result) {
        final List<CourierPK> list = new ArrayList<>();
        if (result != null) {
            try {
                while (result.next()) {
                    list.add(new CourierPK(result.getInt("Cod_corriere"), result.getString("Codice_fiscale"),
                            result.getString("Nome"), result.getString("Cognome"),
                            DateConverter.sqlDateToDate(result.getDate("Data_di_nascita")),
                            result.getString("Cod_patente"), result.getString("Nazionalità_patente")));
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return list;
    }

    @Override
    public List<CourierPK> findAll() {
        final String query = "SELECT * FROM " + TABLE_NAME;
        try (final PreparedStatement statement = this.conn.prepareStatement(query)) {
            var result = statement.executeQuery();
            return convertResultSet(result);
        } catch (final SQLException e) {
            return List.of();
        }
    }

    /**
     * Saves the Courier into the db
     */
    public boolean save(Courier value) {
        final String query = "INSERT INTO " + TABLE_NAME + " (Codice_fiscale, Nome, Cognome,"
                + " Data_di_nascita, Cod_patente, Nazionalità_patente) VALUES (?,?,?,?,?)";

        try (final PreparedStatement statement = this.conn.prepareStatement(query)) {
            statement.setString(1, value.getCodFis());
            statement.setString(2, value.getName());
            statement.setDate(3, DateConverter.dateToSqlDate(value.getDateBirth()));
            statement.setString(4, value.getCodDrivingLic());
            statement.setString(5, value.getDrivingNat());
            final var r = statement.executeUpdate();
            return r == 1;
        } catch (final SQLException e) {
            return false;
        }
    }

    /**
     * {@inheritDoc} Since the Cod_corriere is a value generated by the Database,
     * all CourierPK will be cast to Courier and Cod_courier values will be ignored
     */
    @Override
    public boolean save(CourierPK value) {
        return this.save(CourierPK.convertToCourier(value));
    }

    /**
     * This method return the last Cod courier inserted into the db. This operation
     * is safe if the latest insertion was possibile and no other insertions were
     * made meanwhile this method was called
     * 
     * @returns the Cod Courier or -1 if the db is empty
     */
    public int getLastCourierSaved() {

        final String query = "SELECT * FROM " + TABLE_NAME + " ORDER BY DESC";
        try (final PreparedStatement statement = this.conn.prepareStatement(query)) {
            var result = statement.executeQuery();
            if (result != null && convertResultSet(result).stream().findFirst().isPresent()) {
                return convertResultSet(result).stream().findFirst().get().getCod_corriere();
            } else {
                return -1;
            }

        } catch (final SQLException e) {
            return -1;
        }

    }

    @Override
    public boolean update(CourierPK value) {
        final String query = "UPDATE " + TABLE_NAME + " SET Codice_fiscale=?, Nome=?, Cognome=?,"
                + " Data_di_nascita=?, Cod_patente=?, Nazionalità_patente=? WHERE Cod_corriere=?";

        try (final PreparedStatement statement = this.conn.prepareStatement(query)) {
            statement.setString(1, value.getCodFis());
            statement.setString(2, value.getName());
            statement.setDate(3, DateConverter.dateToSqlDate(value.getDateBirth()));
            statement.setString(4, value.getCodDrivingLic());
            statement.setString(5, value.getDrivingNat());
            statement.setInt(6, value.getCod_corriere());
            final var r = statement.executeUpdate();
            return r == 1;
        } catch (final SQLException e) {
            return false;
        }
    }

    @Override
    public boolean delete(Integer primaryKey) {
        final String query = "DELETE FROM " + TABLE_NAME + " WHERE Cod_corriere=?";

        try (final PreparedStatement statement = this.conn.prepareStatement(query)) {
            statement.setInt(1, primaryKey);
            final var r = statement.executeUpdate();
            return r == 1;
        } catch (final SQLException e) {
            return false;
        }
    }

}
